name: PTR 1e CD

on:
  workflow_run:
    workflows: ["PTR 1e CI"]
    types:
        - completed
    branches:
        - release
  push:
    branches: [release]

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 24.x
              uses: actions/setup-node@v4
              with:
                  node-version: 24.x

            - name: Install 7-Zip
              run: sudo apt-get install -y p7zip-full

            - name: Build
              run: |
                  npm ci
                  npm run build:packs

            - name: Compile LESS to CSS
              run: |
                  npm install -g less
                  lessc less/main.less static/css/main.css

            - name: Update Manifest
              run: |
                  SYSTEM_VERSION=$(grep -oP '(?<="version": ")[^"]+' system.json | tr -d '\n')
                  perl -pi -E "s|latest/download/system\\.zip|download/$SYSTEM_VERSION/system.zip|" system.json
                  echo "systemVersion=$SYSTEM_VERSION" >> $GITHUB_ENV

            - name: Zip Files
              working-directory: .
              run: |
                  7z a -tzip system.zip ./* -x!packs/_source -x!.github -x!.vscode -x!node_modules -x!package.json -x!less -x!package-lock.json -x!scripts -x!utils

            - name: Create Version Release
              id: create_version_release
              uses: ncipollo/release-action@v1
              with:
                  name: ${{ env.systemVersion }}
                  allowUpdates: false
                  draft: false
                  prerelease: false
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: "./system.json,./system.zip"
                  tag: ${{ env.systemVersion }}
